version: "3"
services:
  wordlewise:
    build: .
    ports:
      - "5000:5000"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_S3_OBJECT_NAME
      - AWS_SECRET_ACCESS_KEY
      - JWT_SECRET_KEY